default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates   
    get_provisioning_profile
    increment_build_number(xcodeproj: "bank-product-list.xcodeproj")
    build_app(scheme: "bank-product-list")
    upload_to_testflight
  end
end
