default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates
    get_provisioning_profile
    build_app(scheme: "bank-product-list")
    upload_to_testflight
  end
end
